<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search products
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["products/new", "Create products"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "products/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["name", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldManual" class="col-sm-2 control-label">Manual</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["manual", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldManual"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImage" class="col-sm-2 control-label">Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["image", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldImage"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRawData" class="col-sm-2 control-label">Raw Of Data</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["raw_data", "size" => 30, "class" => "form-control", "id" => "fieldRawData"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldExtension" class="col-sm-2 control-label">Extension</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["extension", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldExtension"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
